name: Lumaris
version: 1.1
main: lumaris.Main
api-version: 1.21
commands:
  hub:
    description: Teleport to the hub.
  adminhub:
    description: Teleport to the admin hub.
    permission: lumaris.admin
  party:
    description: Main party and queue command.
    aliases: [p]
    usage: /party <new|add|accept/join|queue/q|leavequeue/dq|leave|list|kick|promote>
  spawnnpc:
    description: Spawn the Battle Box mannequin.
    permission: lumaris.admin
  partychat:
    description: Chat with your party.
    aliases: [pc]
  dolphinfun:
    description: Hi.
  spawnbattleitem:
    description: Spawns an item from the battle gamemode.
  viewfriends:
    description: Check your friends list.
  addfriend:
    description: Send a friend invitation.
  removefriend:
    description: Remove a user from your friends list.
  invitefriend:
    description: Invite a friend to your current party.
  acceptfriend:
    description: Accept an incoming friend invitation.
  declinefriend:
    description: Decline an incoming friend invitation.