name: Lumaris
version: 1.0
main: lumaris.Main
api-version: 1.21
commands:
  hub:
    description: Teleport to the hub.
  party:
    description: Main party and queue command.
  spawnnpc:
    description: Spawn the Battle Box mannequin.
    permission: lumaris.admin
  pc:
    description: Chat with your party.