name: Lumaris
version: 1.1
main: lumaris.Main
api-version: 1.21
commands:
  hub:
    description: Teleport to the hub.
  party:
    description: Main party and queue command.
    aliases: [p]
    usage: /party <new|add|accept/join|queue/q|leavequeue/dq|leave|list>
  spawnnpc:
    description: Spawn the Battle Box mannequin.
    permission: lumaris.admin
  partychat:
    description: Chat with your party.
    aliases: [pc]