name: Lumaris              # The name of your plugin
version: 1.0               # Plugin version
main: Burpld.lumaris.Lumaris  # Full path to your main Java class
api-version: 1.21          # Minecraft version compatibility

commands:                  # List of commands your plugin provides
  spawn:
    description: Teleports you to spawn  # Description shown in /help
    usage: /spawn                        # Usage info